### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WellImDumb** [Sanaxen/tecoGAN_app#2]
When I click the super resolution button (after loading the input) it will open a window with japanese text and OK button after clicking the OK button it will just END. (I installed tenserflow==1.15.0)

**Comment by Sanaxen** [comment]
There is a possibility of execution error of tensoflow1.15.
In most cases, the installation will not succeed or something will be missing at runtime.
In my execution environment, my antivirus application sometimes deleted some files.

Please use this to see.
https://github.com/Sanaxen/tecoGAN_app/releases/download/0.1.1b/dist.7z

We have confirmed normal operation with tensoflow 1.15.

**Comment by WellImDumb** [comment]
It works now
