### ISSUE TITLE
Could you please build a CPU AVX version of tecoGAN?

### ISSUE THREAD

**Issue by cuppasama** [Sanaxen/tecoGAN_app#9]
CPU processing is way too slow, could it be a little faster with AVX compatible tensorflow? 
Many Thanks!

**Comment by Sanaxen** [comment]
We don't have time right now to work on making your desired feature workable.
I apologize for that.

**Comment by cuppasama** [comment]
> 
> 
> We don't have time right now to work on making your desired feature workable.
> I apologize for that.

Thanks any way.
